In [1]:
#Import dependencies
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import os
from collections import Counter
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from imblearn.combine import SMOTEENN
import sqlalchemy as sa
from sqlalchemy import create_engine
import psycopg2 as pg
from sklearn.metrics import classification_report
import tensorflow as tf

# Connect to database

In [2]:
#Connect to Postgresql database 
conn=sa.create_engine('postgresql://root:postgres@dataanalyticsdb.cxnhjzyey4ka.us-east-2.rds.amazonaws.com:5432/coursefinalproject')

# Load data and perform data cleaning

In [3]:
#Load and display data
df=pd.read_sql_query("SELECT * FROM fragmingham", con=conn)
df

sex  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0       1   39        4.0              0         0.0     0.0                0   
1       0   46        2.0              0         0.0     0.0                0   
2       1   48        1.0              1        20.0     0.0                0   
3       0   61        3.0              1        30.0     0.0                0   
4       0   46        3.0              1        23.0     0.0                0   
...   ...  ...        ...            ...         ...     ...              ...   
3653    1   50        1.0              1         1.0     0.0                0   
3654    1   51        3.0              1        43.0     0.0                0   
3655    0   52        2.0              0         0.0     0.0                0   
3656    1   40        3.0              0         0.0     0.0                0   
3657    0   39        3.0              1        30.0     0.0                0   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  \
0                0         0    195.0  106.0   70.0  26.97       80.0   
1                0         0    250.0  121.0   81.0  28.73       95.0   
2                0         0    245.0  127.5   80.0  25.34       75.0   
3                1         0    225.0  150.0   95.0  28.58       65.0   
4                0         0    285.0  130.0   84.0  23.10       85.0   
...            ...       ...      ...    ...    ...    ...        ...   
3653             1         0    313.0  179.0   92.0  25.97       66.0   
3654             0         0    207.0  126.5   80.0  19.71       65.0   
3655             0         0    269.0  133.5   83.0  21.47       80.0   
3656             1         0    185.0  141.0   98.0  25.60       67.0   
3657             0         0    196.0  133.0   86.0  20.91       85.0   

      glucose  TenYearCHD  
0        77.0           0  
1        76.0           0  
2        70.0           0  
3       103.0           1  
4        85.0           0  
...       ...         ...  
3653     86.0           1  
3654     68.0           0  
3655    107.0           0  
3656     72.0           0  
3657     80.0           0  

[3658 rows x 16 columns]

In [4]:
#Diplay column names
df.columns

Index(['sex', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [5]:
#Explore data types
df.dtypes

sex                  int64
age                  int64
education          float64
currentSmoker        int64
cigsPerDay         float64
BPMeds             float64
prevalentStroke      int64
prevalentHyp         int64
diabetes             int64
totChol            float64
sysBP              float64
diaBP              float64
BMI                float64
heartRate          float64
glucose            float64
TenYearCHD           int64
dtype: object

In [6]:
#Explore for null value
df.isnull().sum()

sex                0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [7]:
#Find duplicates
print(f'Duplicate entries:{df.duplicated().sum()}')

Duplicate entries:0


In [8]:
#Drop unncessary columns and display DataFrame
df.drop(columns=['currentSmoker','diabetes','BPMeds','prevalentStroke'], inplace=True)
df

sex  age  education  cigsPerDay  prevalentHyp  totChol  sysBP  diaBP  \
0       1   39        4.0         0.0             0    195.0  106.0   70.0   
1       0   46        2.0         0.0             0    250.0  121.0   81.0   
2       1   48        1.0        20.0             0    245.0  127.5   80.0   
3       0   61        3.0        30.0             1    225.0  150.0   95.0   
4       0   46        3.0        23.0             0    285.0  130.0   84.0   
...   ...  ...        ...         ...           ...      ...    ...    ...   
3653    1   50        1.0         1.0             1    313.0  179.0   92.0   
3654    1   51        3.0        43.0             0    207.0  126.5   80.0   
3655    0   52        2.0         0.0             0    269.0  133.5   83.0   
3656    1   40        3.0         0.0             1    185.0  141.0   98.0   
3657    0   39        3.0        30.0             0    196.0  133.0   86.0   

        BMI  heartRate  glucose  TenYearCHD  
0     26.97       80.0     77.0           0  
1     28.73       95.0     76.0           0  
2     25.34       75.0     70.0           0  
3     28.58       65.0    103.0           1  
4     23.10       85.0     85.0           0  
...     ...        ...      ...         ...  
3653  25.97       66.0     86.0           1  
3654  19.71       65.0     68.0           0  
3655  21.47       80.0    107.0           0  
3656  25.60       67.0     72.0           0  
3657  20.91       85.0     80.0           0  

[3658 rows x 12 columns]

In [9]:
#Display basic statistical info
df.describe()

sex          age    education   cigsPerDay  prevalentHyp  \
count  3658.000000  3658.000000  3658.000000  3658.000000   3658.000000   
mean      0.443685    49.551941     1.980317     9.025424      0.311646   
std       0.496886     8.562029     1.022656    11.921590      0.463229   
min       0.000000    32.000000     1.000000     0.000000      0.000000   
25%       0.000000    42.000000     1.000000     0.000000      0.000000   
50%       0.000000    49.000000     2.000000     0.000000      0.000000   
75%       1.000000    56.000000     3.000000    20.000000      1.000000   
max       1.000000    70.000000     4.000000    70.000000      1.000000   

           totChol        sysBP        diaBP          BMI    heartRate  \
count  3658.000000  3658.000000  3658.000000  3658.000000  3658.000000   
mean    236.847731   132.370558    82.917031    25.782802    75.730727   
std      44.097681    22.086866    11.974258     4.065601    11.981525   
min     113.000000    83.500000    48.000000    15.540000    44.000000   
25%     206.000000   117.000000    75.000000    23.080000    68.000000   
50%     234.000000   128.000000    82.000000    25.380000    75.000000   
75%     263.000000   143.875000    90.000000    28.037500    82.000000   
max     600.000000   295.000000   142.500000    56.800000   143.000000   

           glucose   TenYearCHD  
count  3658.000000  3658.000000  
mean     81.852925     0.152269  
std      23.904164     0.359331  
min      40.000000     0.000000  
25%      71.000000     0.000000  
50%      78.000000     0.000000  
75%      87.000000     0.000000  
max     394.000000     1.000000

# Split the data into training and testing

In [10]:
#Create features
X=df.copy()
X=X.drop(columns='TenYearCHD')

#Create target
y=df[['TenYearCHD']]

y.shape

(3658, 1)

In [11]:
#Check balance of target values
y['TenYearCHD'].value_counts()

0    3101
1     557
Name: TenYearCHD, dtype: int64

In [12]:
#Split data into Train and Test Sets
X_train, X_test, y_train, y_test=train_test_split(X,y, random_state=1, stratify=y)
print(f'Xtrain:{len(X_train)}')
print(f'y_train:{len(y_train)}')
print(f'X_test:{len(X_test)}')
print(f'y_test:{len(y_test)}')

Xtrain:2743
y_train:2743
X_test:915
y_test:915


# Scale the  data

In [13]:
#Create a StandardScaler instance
scaler=StandardScaler()

#Fit StandardScaler()
X_scaler=scaler.fit(X_train)

#Scaling data
X_train_scaled=X_scaler.transform(X_train)

X_test_scaled=X_scaler.transform(X_test)

# SMOTEENN and Logistic Regression

In [14]:
#Resample the training data SMOTEENN
smote_enn=SMOTEENN(random_state=1)
X_resampled, y_resampled=smote_enn.fit_resample(X_train_scaled,y_train)


In [15]:
print(len(X_resampled))
print(len(y_resampled))

3474
3474


In [16]:
#Train the model
model=LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [17]:
#Calculate de balanced accuracy score
y_pred=model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.633441185196173

In [18]:
#Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[369, 407],
       [ 29, 110]], dtype=int64)

In [19]:
#Display confusion maxtrix as a DataFrame
cm=confusion_matrix(y_test, y_pred)
cm_df=pd.DataFrame(cm, index=['Actual 0','Actual 1'], columns=['Predicted 0', 'Predicted 1'])
cm_df

Predicted 0  Predicted 1
Actual 0          369          407
Actual 1           29          110

In [20]:
#Print the imbalanced classification report
print (classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.93      0.48      0.79      0.63      0.61      0.36       776
          1       0.21      0.79      0.48      0.34      0.61      0.39       139

avg / total       0.82      0.52      0.74      0.58      0.61      0.37       915



#   Balanced Random Forest Classifier

In [21]:
#Train the EasyEnsembleClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

brf=BalancedRandomForestClassifier(n_estimators=100, random_state=1)
brf.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=1)

In [22]:
#Calculate the balanced accuracy score
y_pred=brf.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6581992138248165

In [23]:
#Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[480, 296],
       [ 42,  97]], dtype=int64)

In [24]:
#Print the imbalanced classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.62      0.74       776
           1       0.25      0.70      0.36       139

    accuracy                           0.63       915
   macro avg       0.58      0.66      0.55       915
weighted avg       0.82      0.63      0.68       915



In [25]:
#List the features sorted in descending order by feature importance
importances=brf.feature_importances_
sorted(zip(brf.feature_importances_, X.columns), reverse=True)

[(0.16028440569225996, 'age'),
 (0.14133627758024617, 'sysBP'),
 (0.12220760269407348, 'BMI'),
 (0.11597676379497396, 'glucose'),
 (0.11411974940505758, 'totChol'),
 (0.11031162956352512, 'diaBP'),
 (0.09203469908252443, 'heartRate'),
 (0.05953857175147752, 'cigsPerDay'),
 (0.03736546068556977, 'education'),
 (0.025314681805582454, 'sex'),
 (0.021510157944709497, 'prevalentHyp')]

# Easy Ensemble Classifier

In [26]:
from imblearn.ensemble import EasyEnsembleClassifier
eec=EasyEnsembleClassifier(n_estimators=100, random_state=1)
eec.fit(X_train, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [27]:
# Calculated the balanced accuracy score
y_pred=eec.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6599189720388637

In [28]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[505, 271],
       [ 46,  93]], dtype=int64)

In [29]:
# Print the imbalanced classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.65      0.76       776
           1       0.26      0.67      0.37       139

    accuracy                           0.65       915
   macro avg       0.59      0.66      0.57       915
weighted avg       0.82      0.65      0.70       915



# Random oversampling

In [30]:
# Implement random oversampling
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train_scaled, y_train)


In [31]:
print(X_resampled.shape)
print(y_resampled.shape)

(4650, 11)
(4650, 1)


In [32]:
#Perform Logistic Regression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [33]:
#Make Predictions
y_pred = model.predict(X_test_scaled)
confusion_matrix(y_test, y_pred)

array([[504, 272],
       [ 47,  92]], dtype=int64)

In [34]:
#Display confusion maxtrix as a DataFrame
cm=confusion_matrix(y_test, y_pred)
cm_df=pd.DataFrame(cm, index=['Actual 0','Actual 1'], columns=['Predicted 0', 'Predicted 1'])
cm_df

Predicted 0  Predicted 1
Actual 0          504          272
Actual 1           47           92

In [35]:
#Calculate balanced accuracy score
balanced_accuracy_score(y_test, y_pred)

0.6556775198397983

In [36]:
#Print classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.65      0.76       776
           1       0.25      0.66      0.37       139

    accuracy                           0.65       915
   macro avg       0.58      0.66      0.56       915
weighted avg       0.81      0.65      0.70       915



# SMOTE and Logistic Regression

In [37]:
#Import dependency
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy='auto').fit_resample(X_train_scaled, y_train)

In [38]:
print(X_resampled.shape)
print(y_resampled.shape)

(4650, 11)
(4650, 1)


In [39]:
#Perform Logistic regression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [40]:
#Make predictions
y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.6537445301490766

In [41]:

confusion_matrix(y_test, y_pred)

array([[501, 275],
       [ 47,  92]], dtype=int64)

In [42]:
#Display confusion maxtrix as a DataFrame
cm=confusion_matrix(y_test, y_pred)
cm_df=pd.DataFrame(cm, index=['Actual 0','Actual 1'], columns=['Predicted 0', 'Predicted 1'])
cm_df

Predicted 0  Predicted 1
Actual 0          501          275
Actual 1           47           92

In [43]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.91      0.65      0.66      0.76      0.65      0.43       776
          1       0.25      0.66      0.65      0.36      0.65      0.43       139

avg / total       0.81      0.65      0.66      0.70      0.65      0.43       915



# Neural Network

In [44]:
#Define the basic neural network model
number_input_features=len(X_train_scaled[0])

nn_model=tf.keras.models.Sequential()

#First hidden layer
nn_model.add(tf.keras.layers.Dense(units=80, input_dim=number_input_features, activation='relu'))

#Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=30, activation='relu'))

#Third hidden layer
nn_model.add(tf.keras.layers.Dense(units=30, activation='relu'))

#Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#Check the structure of the model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 80)                960       
                                                                 
 dense_1 (Dense)             (None, 30)                2430      
                                                                 
 dense_2 (Dense)             (None, 30)                930       
                                                                 
 dense_3 (Dense)             (None, 1)                 31        
                                                                 
Total params: 4,351
Trainable params: 4,351
Non-trainable params: 0
_________________________________________________________________


In [45]:
#Compile the model
nn_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [46]:
#Train the model
nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
86/86 [==============================] - 1s 2ms/step - loss: 0.4442 - accuracy: 0.8389
Epoch 2/100
86/86 [==============================] - 0s 3ms/step - loss: 0.3894 - accuracy: 0.8494
Epoch 3/100
86/86 [==============================] - 0s 2ms/step - loss: 0.3808 - accuracy: 0.8520
Epoch 4/100
86/86 [==============================] - 0s 2ms/step - loss: 0.3735 - accuracy: 0.8531
Epoch 5/100
86/86 [==============================] - 0s 2ms/step - loss: 0.3672 - accuracy: 0.8589
Epoch 6/100
86/86 [==============================] - 0s 2ms/step - loss: 0.3635 - accuracy: 0.8578
Epoch 7/100
86/86 [==============================] - 0s 2ms/step - loss: 0.3609 - accuracy: 0.8578
Epoch 8/100
86/86 [==============================] - 0s 2ms/step - loss: 0.3560 - accuracy: 0.8585
Epoch 9/100
86/86 [==============================] - 0s 2ms/step - loss: 0.3530 - accuracy: 0.8604
Epoch 10/100
86/86 [==============================] - 0s 2ms/step - loss: 0.3487 - accuracy: 0.8607
Epoch 11/

86/86 [==============================] - 0s 2ms/step - loss: 0.0743 - accuracy: 0.9756
Epoch 84/100
86/86 [==============================] - 0s 2ms/step - loss: 0.0715 - accuracy: 0.9767
Epoch 85/100
86/86 [==============================] - 0s 2ms/step - loss: 0.0758 - accuracy: 0.9759
Epoch 86/100
86/86 [==============================] - 0s 2ms/step - loss: 0.0954 - accuracy: 0.9632
Epoch 87/100
86/86 [==============================] - 0s 2ms/step - loss: 0.0649 - accuracy: 0.9803
Epoch 88/100
86/86 [==============================] - 0s 2ms/step - loss: 0.0644 - accuracy: 0.9818
Epoch 89/100
86/86 [==============================] - 0s 2ms/step - loss: 0.0607 - accuracy: 0.9821
Epoch 90/100
86/86 [==============================] - 0s 2ms/step - loss: 0.0538 - accuracy: 0.9876
Epoch 91/100
86/86 [==============================] - 0s 2ms/step - loss: 0.0540 - accuracy: 0.9865
Epoch 92/100
86/86 [==============================] - 0s 2ms/step - loss: 0.0618 - accuracy: 0.9799
Epoch 93/100


In [47]:
#Evaluate the model using th test data
model_loss, model_accuracy=nn_model.evaluate(X_test_scaled, y_test, verbose=2)
print(f'Loss: {model_loss}, Accuracy:{model_accuracy}')

29/29 - 0s - loss: 1.4517 - accuracy: 0.7541 - 194ms/epoch - 7ms/step
Loss: 1.451681137084961, Accuracy:0.7540983557701111
